[package]
authors = [ "Gabriel Plassard <2485407+gplassard@users.noreply.github.com>" ]
version = "1.2.0"
edition = "2021"
name = "pretty-logs"

[dependencies]
atty = "0.2.14"
env_logger = "0.10.0"
log = "0.4.16"
structopt = "0.3.26"
